name: Deploy to Github Pages

on:
  push:
    branches:
      - master

jobs:
  Deploy-to-Github-Pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16
          cache: npm

      - name: Install dependencies
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: install

      - name: Generate static site
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: generate

      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .output/public
